services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi_sample_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d fastapi_sample_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data # persist data
  web:
    build: . # use Dockerfile
    command: /app/.venv/bin/uvicorn main:app --proxy-headers --reload --port 8000 --host 0.0.0.0
    ports:
      - 8000:8000
    env_file: ".env"
    depends_on:
      db:
        condition: service_healthy

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data: